[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
ethereum = "https://eth.drpc.org"

[etherscan]
sepolia = { key = "${MOONSCAN_API_KEY}" }
ethereum = { key = "${MOONSCAN_API_KEY}" }